/// 全局常量配置
library;

class AppConstants {
  AppConstants._();

  // 应用信息
  static const String appName = '智伴口袋';
  static const String appNameEn = 'PocketMind';
  static const String appVersion = '1.2.1';

  // 缓存Key
  static const String keyModuleConfig = 'moduleConfig';
  static const String keyDailyContentPrefix = 'daily_';
  static const String keyUserInfo = 'userInfo';
  static const String keyLastSyncTime = 'lastSyncTime';

  // 缓存过期时间（小时）
  static const int cacheExpireHours = 24;

  // 腾讯云CloudBase配置
  static const String cloudbaseEnvId = 'YOUR_ENVID'; // TODO: 替换为实际环境ID

  //默认模型
  static const String defaultModel = 'hunyuan-exp';
  static const String defaultSubModel = 'hunyuan-turbos-latest';

    // 模块类型枚举
  static const Map<String, String> moduleTypes = {
    'quote': '每日名言',
    'joke': '幽默笑话',
    'psychology': '心理学',
    'finance': '财经',
    'love': '爱情语录',
    'movie': '电影推荐',
    'music': '音乐分享',
    'tech': '科技前沿',
    'tcm': '中医养生',
    'travel': '旅行攻略',
    'fortune': '每日运势',
    'literature': '文学赏析',
    'foreignTrade': '外贸资讯',
    'ecommerce': '电商动态',
    'math': '数学趣题',
    'english': '英语学习',
    'programming': '编程技巧',
    'photography': '摄影技巧',
    'beauty': '美容护肤',
    'investment': '投资理财',
    'fishing': '钓鱼技巧',
    'fitness': '健身指导',
    'pet': '宠物养护',
    'fashion': '时尚穿搭',
    'outfit': '穿搭推荐',
    'decoration': '家居装饰',
    'glassFiber': '玻璃纤维',
    'resin': '树脂工艺',
    'tax': '税务筹划',
    'law': '法律常识',
    'official': '政务服务',
    'handling': '办事指南',
    'floral': '花卉养护',
    'history': '历史故事',
    'military': '军事动态',
    'stock': '股市行情',
    'economics': '经济观察',
    'business': '商业洞察',
    'news': '每日资讯',
    'apple': '果核学堂',
    'growth': '市场品牌增长专家',
    'uiDesigner': 'UI设计师专家',
    'futures': '大宗贸易期货专家',
    'freud': '弗洛伊德学术专家',
    'fashionBrand': '世界服装品牌大师',
    'robotAi': '机器人AI专家',
    'americanExpert': '美国通',
    'xinStudy': '心学大师',
    'liStudy': '理学大师',
    'wisdomBag': '智慧锦囊',
    'anthropologist': '人类学家',
    'geographer': '地理学家',
    'historian': '历史学家',
    'narratologist': '叙事学家',
    'psychologist': '心理学家',
    'softwareArchitect': '软件架构师助手',
    'solidityEngineer': 'Solidity智能合约工程师',
    'xiaohongshuExpert': '小红书专家',
    'seoExpert': 'SEO专家',
  };

    // 默认模块配置（兜底数据）
  static const List<Map<String, dynamic>> defaultModules = [
    {
      'id': 'quote',
      'name': '每日名言',
      'icon': '📜',
      'color': '#FF6B6B',
      'description': '名言警句，每日一句，点亮你的一天',
      'generate': '请生成一句经典名言，包含作者和出处',
    },
    {
      'id': 'joke',
      'name': '幽默笑话',
      'icon': '😄',
      'color': '#4ECDC4',
      'description': '轻松一刻，快乐每一天',
      'generate': '请生成一个简短有趣的笑话',
    },
    {
      'id': 'psychology',
      'name': '心理学',
      'icon': '🧠',
      'color': '#9B59B6',
      'description': '心理小知识，了解自己了解他人',
      'generate': '请生成一个实用的心理学小知识',
    },
    {
      'id': 'finance',
      'name': '财经',
      'icon': '💰',
      'color': '#27AE60',
      'description': '投资理财，财富增长',
      'generate': '请生成一条实用的理财小知识',
    },
    {
      'id': 'love',
      'name': '爱情语录',
      'icon': '💕',
      'color': '#E91E63',
      'description': '浪漫语录，温暖你的心',
      'generate': '请生成一条浪漫的爱情语录',
    },
    {
      'id': 'movie',
      'name': '电影推荐',
      'icon': '🎬',
      'color': '#3498DB',
      'description': '精彩电影，不容错过',
      'generate': '请生成一部值得观看的电影推荐',
    },
    {
      'id': 'music',
      'name': '音乐分享',
      'icon': '🎵',
      'color': '#F39C12',
      'description': '经典音乐，打动人心',
      'generate': '请推荐一首经典歌曲',
    },
    {
      'id': 'tech',
      'name': '科技前沿',
      'icon': '🔬',
      'color': '#1ABC9C',
      'description': '科技动态，洞见未来',
      'generate': '请分享一个科技前沿动态',
    },
    {
      'id': 'tcm',
      'name': '中医养生',
      'icon': '🌿',
      'color': '#2ECC71',
      'description': '中医养生，健康生活',
      'generate': '请分享一个中医养生小知识',
    },
    {
      'id': 'travel',
      'name': '旅行攻略',
      'icon': '🌍',
      'color': '#E67E22',
      'description': '旅行推荐，玩转世界',
      'generate': '请推荐一个旅行目的地',
    },
    {
      'id': 'fortune',
      'name': '每日运势',
      'icon': '🔮',
      'color': '#8E44AD',
      'description': '每日运势，好运相伴',
      'generate': '请生成今日运势分析',
    },
    {
      'id': 'literature',
      'name': '文学赏析',
      'icon': '📖',
      'color': '#D35400',
      'description': '文学佳作，细细品读',
      'generate': '请分享一段文学佳作赏析',
    },
    {
      'id': 'foreignTrade',
      'name': '外贸资讯',
      'icon': '🌐',
      'color': '#16A085',
      'description': '外贸资讯，商机无限',
      'generate': '请分享一条外贸资讯',
    },
    {
      'id': 'ecommerce',
      'name': '电商动态',
      'icon': '🛒',
      'color': '#2980B9',
      'description': '电商动态，把握趋势',
      'generate': '请分享一个电商运营知识',
    },
    {
      'id': 'math',
      'name': '数学趣题',
      'icon': '🔢',
      'color': '#8E44AD',
      'description': '数学趣题，启迪思维',
      'generate': '请分享一个有趣的数学知识',
    },
    {
      'id': 'english',
      'name': '英语学习',
      'icon': '🇬🇧',
      'color': '#C0392B',
      'description': '英语学习，提升自我',
      'generate': '请分享一个实用的英语知识点',
    },
    {
      'id': 'programming',
      'name': '编程技巧',
      'icon': '💻',
      'color': '#27AE60',
      'description': '编程技巧，技术进阶',
      'generate': '请介绍一个有趣的编程概念',
    },
    {
      'id': 'photography',
      'name': '摄影技巧',
      'icon': '📷',
      'color': '#D68910',
      'description': '摄影技巧，记录美好',
      'generate': '请分享一个实用的摄影技巧',
    },
    {
      'id': 'beauty',
      'name': '美容护肤',
      'icon': '💄',
      'color': '#F38D9C',
      'description': '美容护肤，焕发光彩',
      'generate': '请分享一个实用的美容护肤知识',
    },
    {
      'id': 'investment',
      'name': '投资理财',
      'icon': '📈',
      'color': '#1E8449',
      'description': '投资理财，财富增值',
      'generate': '请分享一个投资理财知识',
    },
    {
      'id': 'fishing',
      'name': '钓鱼技巧',
      'icon': '🎣',
      'color': '#3498DB',
      'description': '钓鱼技巧，渔乐无穷',
      'generate': '请分享一个钓鱼技巧或知识',
    },
    {
      'id': 'fitness',
      'name': '健身指导',
      'icon': '💪',
      'color': '#E74C3C',
      'description': '健身指导，强健体魄',
      'generate': '请分享一个实用的健身知识',
    },
    {
      'id': 'pet',
      'name': '宠物养护',
      'icon': '🐾',
      'color': '#9B59B6',
      'description': '宠物养护，爱心陪伴',
      'generate': '请分享一个宠物养护知识',
    },
    {
      'id': 'fashion',
      'name': '时尚穿搭',
      'icon': '👗',
      'color': '#F39C12',
      'description': '时尚穿搭，展现品味',
      'generate': '请分享一个时尚穿搭知识',
    },
    {
      'id': 'outfit',
      'name': '穿搭推荐',
      'icon': '👔',
      'color': '#E91E63',
      'description': '穿搭推荐，每日搭配',
      'generate': '请分享一个穿搭推荐',
    },
    {
      'id': 'decoration',
      'name': '家居装饰',
      'icon': '🏠',
      'color': '#795548',
      'description': '家居装饰，美化生活',
      'generate': '请分享一个家居装饰技巧',
    },
    {
      'id': 'glassFiber',
      'name': '玻璃纤维',
      'icon': '🧪',
      'color': '#607D8B',
      'description': '玻璃纤维，材料前沿',
      'generate': '请分享一个玻璃纤维相关知识',
    },
    {
      'id': 'resin',
      'name': '树脂工艺',
      'icon': '🎨',
      'color': '#00BCD4',
      'description': '树脂工艺，创意无限',
      'generate': '请分享一个树脂工艺知识',
    },
    {
      'id': 'tax',
      'name': '税务筹划',
      'icon': '📋',
      'color': '#FF5722',
      'description': '税务筹划，合规省心',
      'generate': '请分享一个税务筹划知识',
    },
    {
      'id': 'law',
      'name': '法律常识',
      'icon': '⚖️',
      'color': '#455A64',
      'description': '法律常识，知法守法',
      'generate': '请分享一个实用法律常识',
    },
    {
      'id': 'official',
      'name': '政务服务',
      'icon': '🏛️',
      'color': '#2196F3',
      'description': '政务服务，办事指南',
      'generate': '请分享一个政务服务信息',
    },
    {
      'id': 'handling',
      'name': '办事指南',
      'icon': '📝',
      'color': '#4CAF50',
      'description': '办事指南，高效办事',
      'generate': '请分享一个办事指南',
    },
    {
      'id': 'floral',
      'name': '花卉养护',
      'icon': '🌸',
      'color': '#E91E63',
      'description': '花卉养护，芬芳生活',
      'generate': '请分享一个花卉养护知识',
    },
    {
      'id': 'history',
      'name': '历史故事',
      'icon': '📜',
      'color': '#795548',
      'description': '历史故事，以史为鉴',
      'generate': '请分享一个有趣的历史故事',
    },
    {
      'id': 'military',
      'name': '军事动态',
      'icon': '⚔️',
      'color': '#607D8B',
      'description': '军事动态，国防视野',
      'generate': '请分享一条军事动态',
    },
    {
      'id': 'stock',
      'name': '股市行情',
      'icon': '📊',
      'color': '#F44336',
      'description': '股市行情，投资参考',
      'generate': '请分享一条股市行情分析',
    },
    {
      'id': 'economics',
      'name': '经济观察',
      'icon': '📉',
      'color': '#FF9800',
      'description': '经济观察，洞悉趋势',
      'generate': '请分享一条经济观察',
    },
    {
      'id': 'business',
      'name': '商业洞察',
      'icon': '💼',
      'color': '#673AB7',
      'description': '商业洞察，把握商机',
      'generate': '请分享一个商业洞察',
    },
    {
      'id': 'news',
      'name': '每日资讯',
      'icon': '📰',
      'color': '#00BCD4',
      'description': '每日资讯，知晓天下',
      'generate': '请生成一条每日资讯',
    },
    {
      'id': 'apple',
      'name': '果核学堂',
      'icon': '🍎',
      'color': '#007AFF',
      'description': '果核学堂，智慧果实',
      'generate': '请分享一个有趣的知识点',
    },
    {
      'id': 'growth',
      'name': '市场品牌增长专家',
      'icon': '📈',
      'color': '#E91E63',
      'description': '市场品牌增长策略',
      'generate': '请分享一个品牌增长策略',
    },
    {
      'id': 'uiDesigner',
      'name': 'UI设计师专家',
      'icon': '🎨',
      'color': '#9C27B0',
      'description': 'UI设计，视觉美学',
      'generate': '请分享一个UI设计技巧',
    },
    {
      'id': 'futures',
      'name': '大宗贸易期货专家',
      'icon': '📊',
      'color': '#FF5722',
      'description': '期货贸易，专业分析',
      'generate': '请分享一个期货贸易知识',
    },
    {
      'id': 'freud',
      'name': '弗洛伊德学术专家',
      'icon': '🧠',
      'color': '#6D4C41',
      'description': '弗洛伊德心理学',
      'generate': '请分享一个弗洛伊德心理学概念',
    },
    {
      'id': 'fashionBrand',
      'name': '世界服装品牌大师',
      'icon': '👘',
      'color': '#D4AF37',
      'description': '服装品牌，时尚前沿',
      'generate': '请分享一个世界服装品牌故事',
    },
    {
      'id': 'robotAi',
      'name': '机器人AI专家',
      'icon': '🤖',
      'color': '#7C4DFF',
      'description': '人工智能，未来科技',
      'generate': '请分享一个机器人或AI知识',
    },
    {
      'id': 'americanExpert',
      'name': '美国通',
      'icon': '🇺🇸',
      'color': '#3F51B5',
      'description': '美国文化，深入了解',
      'generate': '请分享一个关于美国的知识',
    },
    {
      'id': 'xinStudy',
      'name': '心学大师',
      'icon': '🧘',
      'color': '#8B0000',
      'description': '心学智慧，修身养性',
      'generate': '请分享一个心学知识点',
    },
    {
      'id': 'liStudy',
      'name': '理学大师',
      'icon': '📚',
      'color': '#1E3A5F',
      'description': '理学思想，格物致知',
      'generate': '请分享一个理学知识点',
    },
    {
      'id': 'wisdomBag',
      'name': '智慧锦囊',
      'icon': '🎒',
      'color': '#B8860B',
      'description': '智慧锦囊，人生哲理',
      'generate': '请分享一个智慧锦囊',
    },
    {
      'id': 'anthropologist',
      'name': '人类学家',
      'icon': '🗿',
      'color': '#5D4037',
      'description': '人类学视角看世界',
      'generate': '请分享一个人类学知识',
    },
    {
      'id': 'geographer',
      'name': '地理学家',
      'icon': '🗺️',
      'color': '#1B5E20',
      'description': '地理知识，探索世界',
      'generate': '请分享一个地理知识',
    },
    {
      'id': 'historian',
      'name': '历史学家',
      'icon': '🏺',
      'color': '#4527A0',
      'description': '历史研究，深度解读',
      'generate': '请分享一个历史研究视角',
    },
    {
      'id': 'narratologist',
      'name': '叙事学家',
      'icon': '📝',
      'color': '#880E4F',
      'description': '叙事艺术，故事力量',
      'generate': '请分享一个叙事学概念',
    },
    {
      'id': 'psychologist',
      'name': '心理学家',
      'icon': '🧠',
      'color': '#303F9F',
      'description': '心理学深度解读',
      'generate': '请分享一个心理学研究成果',
    },
    {
      'id': 'softwareArchitect',
      'name': '软件架构师助手',
      'icon': '🖥️',
      'color': '#1565C0',
      'description': '软件架构，系统设计',
      'generate': '请分享一个软件架构知识',
    },
    {
      'id': 'solidityEngineer',
      'name': 'Solidity智能合约工程师',
      'icon': '🔗',
      'color': '#2E7D32',
      'description': '智能合约，区块链开发',
      'generate': '请分享一个智能合约知识',
    },
    {
      'id': 'xiaohongshuExpert',
      'name': '小红书专家',
      'icon': '📕',
      'color': '#E91E63',
      'description': '小红书运营，种草技巧',
      'generate': '请分享一个小红书运营技巧',
    },
    {
      'id': 'seoExpert',
      'name': 'SEO专家',
      'icon': '🔍',
      'color': '#FF5722',
      'description': '搜索引擎优化，让内容被更多人看到',
      'generate': '请生成一条SEO优化技巧',
    },
  ];
}